version: 2

updates:
    - package-ecosystem: "gomod"
      schedule:
          interval: "daily"
      ignore:
          - dependency-name: "*"
            update-types:
                - version-update:semver-minor
                - version-update:semver-patch

    - package-ecosystem: "docker"
      schedule:
          interval: "daily"
      ignore:
          - dependency-name: "*"
            update-types:
                - version-update:semver-minor
                - version-update:semver-patch

    - package-ecosystem: "github-actions"
      schedule:
          interval: "daily"
      ignore:
          - dependency-name: "*"
            update-types:
                - version-update:semver-minor
                - version-update:semver-patch
