services:
    app:
        image: app:latest
        build:
            context: .
            target: app

    test:
        image: test:latest
        build:
            context: .
            target: test
        environment:
            API_URL: http://app:8080
        depends_on:
            app:
                condition: service_healthy
